#!/usr/bin/env bash

install_packages() {
    printf 'Installing packages for Arch Linux...\n'

    packages=(
        "xorg-server"
        "xorg-xinit"
        "xorg-xrandr"
        "xorg-xsetroot"
        "xorg-xbacklight"
        "xf86-video-intel"
        "xf86-input-libinput"
        "mesa"
        "man-db"
        "man-pages"
        "texinfo"
        "imagemagick"
        "alsa-utils"
        "alsa-lib"
        "pulseaudio"
        "pamixer"
        "dmenu"
        "i3-gaps"
        "i3lock"
        "conky"
        "dunst"
        "kitty"
        "w3m"
        "picom"
        "hsetroot"
        "firefox"
        "chromium"
        "gimp"
        "inkscape"
        "gtop"
        "ranger"
        "neofetch"
        "scrot"
        "newsboat"
        "zip"
        "unzip"
        "p7zip"
        "npm"
        "docker"
        "docker-compose"
        "openssh"
        "zathura"
        "poppler"
        "zathura-pdf-poppler"
        "python-pip"
        "python-pillow"
        "jshon"
        "jq"
        "noto-fonts-emoji"
        "gnu-netcat"
        "tree"
    )

    sudo pacman -Syu "${packages[@]}"

    printf "Done.\n"
}

install_packages
