#!/bin/bash

###############
### ALIASES ###
###############

alias clr="clear"
alias la="ls -AFGghl"
alias las="ls -AFG"
alias gc="git commit"
alias gcm="git commit -m"
alias gpuom="git push -u origin master"
alias gpom="git push origin master"
alias gpuo="git push -u origin"
alias gpo="git push origin"
alias gp="git push"
alias gs="git status"
alias gss="git status -s"
alias giff="git diff"
alias gslog="git shortlog"
alias glog="git log --pretty=format:'%n%ar %n%Cred%h %Cblue%an <%ae> %n%Cgreen%s%n' --name-only"
alias glogme="glog --author='\(Felix\)\|\(fehawen\)'"
alias gcount="git shortlog -s -n -e --all"
alias gscount="git rev-list --all --count"
alias code="open -a 'Visual Studio Code'"
alias gh="cd ~/Github/"
alias repos="cd ~/Github/"
alias dot="cd ~/Dotfiles/"
alias pro="cd ~/projects/"
alias mongorun="mongod --dbpath ~/paths/mongodb-osx-x86_64-4.0.3/data"
alias todoread="cat ~/Github/todo/README.md"
alias todoedit="nvim ~/Github/todo/README.md"
alias rr="ranger"
alias icat="kitty +kitten icat"
alias wrls="sudo wifi-menu"
alias screenshot="scrot ~/Github/fehawen-files/screenshots/%Y-%m-%d-%T-screenshot.png -d 10"
alias colorblocks="~/Dotfiles/utils/colorblocks"
alias todopush=push_todos
alias todopull=pull_todos
alias hunt=find_string_in_file
alias mark=find_matching_file_or_subdir
alias scope=find_subdir
alias bklt=set_xbacklight
alias vlme=set_volume
alias wthr=get_weather

#############
### UTILS ###
#############

push_todos() {
	pushd "$HOME/Github/todo/" && \
	git add . && \
	git commit -m "Bump." && \
	git push && \
	cd "$(dirs -l -0)" && dirs -c
}

pull_todos() {
	pushd "$HOME/Github/todo/" && \
	git pull && \
	cd "$(dirs -l -0)" && dirs -c
}

# Find all files in dirs/subdirs containing search query
find_string_in_file() {
	command grep \
		--exclude-dir=node_modules \
		--exclude-dir=.fusebox \
		--exclude-dir=dist \
		--exclude-dir=.git \
		-wroni "${1}" . | sort -u | grep -iv "^${1}" | sed "/^$/d" | grep -i --color=always "${1}"
}

# Find all sbudirs/filenames in dirs/subdirs matching query
find_matching_file_or_subdir() {
	command find . -not -path "*node_modules*" -not -path "*.git*" -not -path "*dist*" -iname "*${1}*" | sort -u | grep -i --color=always "${1}"
}

# Window manager helper for starting, stopping or restarting either chunkwm or skhd
wm() {
	brew services "${1}" koekeishiya/formulae/"${2}"
}

# Change X screen brightness, when backlight keys increments aren't precise enough
set_xbacklight() {
	command xbacklight -set "${1}"
}

# Change volume through pamixer, when colume keys increments aren't precise enough
set_volume() {
	command pamixer --set-volume "${1}"
}

# Get weather report for specified location
# if second argument (optional) is "-f", get 3-day forecast for morning, nnon, evening, night
# else if first argument is only location, get current weather only
get_weather() {
	if [[ "$2" == "-f" ]]; then
		command curl "http://wttr.in/${1}?M"
	else
		command curl "http://wttr.in/${1}?0&M"
	fi
}
