#!/bin/bash

#################
### VARIABLES ###
#################

# arrow_symbol=""
arrow_symbol="›"
exit_symbol="$arrow_symbol"

newline="\n"

ahead_symbol="A"
behind_symbol="B"
# branch_symbol=""
branch_symbol=""
conflicts_symbol="C"
deleted_symbol="D"
modified_symbol="M"
staged_symbol="S"
stashed_symbol="T"
untracked_symbol="U"

prefix_color="$white"
root_color="$red"
dir_color="$cyan"
git_branch_color="$magenta"
git_status_color="$red"
exec_time_color="$yellow"
exit_ok_color="$green"
exit_bad_color="$red"

dir_prefix="in"
git_prefix="on"
git_status_prefix="("
git_status_suffix=")"
exec_time_prefix="took"

###############
### HELPERS ###
###############

is_git_repository() {
	git rev-parse --is-inside-work-tree &> /dev/null
}

timer_start() {
	start_time=${start_time:-$SECONDS}
}

timer_stop() {
	timer=$((SECONDS - start_time))
	unset start_time
}

trap timer_start DEBUG

###############
### MODULES ###
###############

user_module() {
	[[ "$UID" -eq 0 ]] && PS1+="${root_color}$USER ${prefix_color}${dir_prefix} "
}

# -----------------------------------------------------------------------------

dir_module() {
	dir="$(pwd | sed -E -e "s|^$HOME|~|")"
	trim_dir="${dir#"${dir%/*/*}/"}"

	PS1+="${dir_color}${trim_dir}"
}

# -----------------------------------------------------------------------------

git_branch_module() {
	is_git_repository || return

	branch="$(git rev-parse --abbrev-ref HEAD 2> /dev/null)"

	PS1+=" ${prefix_color}${git_prefix} ${git_branch_color}${branch_symbol} ${branch}"
}

# -----------------------------------------------------------------------------

git_status_module() {
	is_git_repository || return

	status=""

	conflicts="$(git diff --name-only --diff-filter=U 2> /dev/null | wc -l)"
	[[ "$conflicts" -gt 0 ]] && status+="${conflicts_symbol}"

	deleted="$(git diff --name-only --diff-filter=D 2> /dev/null | wc -l)"
	[[ "$deleted" -gt 0 ]] && status+="${deleted_symbol}"

	staged="$(git diff --staged --name-only --diff-filter=AM 2> /dev/null | wc -l)"
	[[ "$staged" -gt 0 ]] && status+="${staged_symbol}"

	modified="$(git diff --name-only --diff-filter=M 2> /dev/null | wc -l)"
	[[ "$modified" -gt 0 ]] && status+="${modified_symbol}"

	untracked="$(git ls-files --other --exclude-standard | wc -l)"
	[[ "$untracked" -gt 0 ]] && status+="${untracked_symbol}"

	ahead="$(git rev-list --left-only --count HEAD...@"{u}" 2> /dev/null)"
	[[ "$ahead" -gt 0 ]] && status+="${ahead_symbol}"

	behind="$(git rev-list --left-only --count @"{u}"...HEAD 2> /dev/null)"
	[[ "$behind" -gt 0 ]] && status+="${behind_symbol}"

	stashed="$(git stash list 2> /dev/null)"
	[[ -n "$stashed" ]] && status+="${stashed_symbol}"

	[[ "$status" != "" ]] && PS1+=" ${git_status_color}${git_status_prefix}${status}${git_status_suffix}"
}

# -----------------------------------------------------------------------------

exec_time_module() {
	(( timer < 3 )) && return

	declare output

	days=$(( timer / 86400 ))
	hours=$(( timer / 3600 % 24 ))
	minutes=$(( timer / 60 % 60 ))
	seconds=$(( timer % 60 ))

	(( days > 0 )) && output+="${days}d "
	(( hours > 0 )) && output+="${hours}h "
	(( minutes > 0 )) && output+="${minutes}m "
	output+="${seconds}s"

	PS1+=" ${prefix_color}${exec_time_prefix}${exec_time_color} ${output}"
}

# -----------------------------------------------------------------------------

exit_code_module() {
	if [[ "$RETVAL" -eq 0 ]]; then
		exit_status="${exit_ok_color}"
	else
		exit_status="${exit_bad_color}"
	fi

	PS1+="${newline}${reset}${bold}${exit_status}${exit_symbol}${reset} "
}

####################
### PROMPT ORDER ###
####################

declare -a prompt_modules=(
	"user_module"
	"dir_module"
	"git_branch_module"
	"git_status_module"
	"exec_time_module"
	"exit_code_module"
)

######################
### POINT OF ENTRY ###
######################

compose_prompt() {
	RETVAL=$?

	timer_stop

	PS1=""

	PS1+="${bold}"
	PS1+="${italic}"

	for MODULE in "${!prompt_modules[@]}"; do
		${prompt_modules[$MODULE]}
	done
}

PROMPT_COMMAND="compose_prompt"
