#!/bin/bash

###############
### SYMBOLS ###
###############

# arrow="›"
# arrow="❯"
arrow="→"
git_dirty="D"
git_stashed="S"
git_ahead="A"
git_behind="B"
# git_dirty="→"
# git_stashed="←"
# git_ahead="↑"
# git_behind="↓"

#######################
### SECTION STYLING ###
#######################

# Conventional solution for new line
newline="
"

# Section colors, symbols and prefixes
prefix_color="$white"
root_color="$red"
root_suffix="${prefix_color}in"
dir_color="$blue"
git_prefix="${prefix_color}on"
git_branch_color="$magenta"
git_status_color="$red"
git_status_prefix="["
git_status_suffix="]"
exec_time_color="$yellow"
exec_time_prefix="${prefix_color}took"
exit_ok_color="$green"
exit_bad_color="$red"
exit_symbol="$arrow"

#############
### UTILS ###
#############

# Check if command exists, without printing error if it doesn"t
command_exists() {
	command -v $1 > /dev/null 2>&1
}

# Check if we"re in a git repository, without printing error if we aren"t
is_git_repository() {
	command git rev-parse --is-inside-work-tree &> /dev/null
}

#######################
### PROMPT SECTIONS ###
#######################

timer_start() {
	start_time=${start_time:-$SECONDS}
}

timer_stop() {
	timer=$(($SECONDS - $start_time))
	unset start_time
}

trap timer_start DEBUG

# Prints out user only if we're root, else prints nothing
user_section() {
	[[ "$UID" -eq 0 ]] && echo -e "${root_color}$USER ${root_suffix} "
}

# Prints out current directory and its parent directory, replacing HOME with ~
dir_section() {
	local truncate_cwd="$(pwd | sed -E -e "s|^$HOME|~|" -e 's|^([^/]*/[^/]*/).*(/[^/]*)|\1..\2|')"
	echo -e "${dir_color}${truncate_cwd}"
}

# Show current Git branch, and if branch isn"t clean show status
git_section() {
	is_git_repository || return

	local status=""
	local index="$(git status --porcelain -b 2> /dev/null)"

	local branch="$(git symbolic-ref --quiet --short HEAD 2> /dev/null || git rev-parse --short HEAD 2> /dev/null)"

	local behind="$(git rev-list --left-only --count @"{u}"...HEAD 2> /dev/null)"
	local ahead="$(git rev-list --left-only --count HEAD...@"{u}" 2> /dev/null)"

	local branch_ahead branch_behind

	[[ -n $(git status --short 2> /dev/null) ]] && status="${status}${git_dirty}"

	[[ "$ahead" -gt 0 ]] && status="${status}${git_ahead}"

	[[ "$behind" -gt 0 ]] && status="${status}${git_behind}"

	[[ -n $(git stash list 2> /dev/null) ]] && status="${status}${git_stashed}"

	local git_status="${git_prefix} ${git_branch_color}${branch}"

	[[ "$status" != "" ]] && git_status="${git_status} ${git_status_color}${git_status_prefix}${status}${git_status_suffix}"

	echo -e " ${git_status}"
}

# Command execution time with formatted output as 1d 3h 7m 6s
exec_time_section() {
	(( $timer < 3 )) && return

	local output=""

	local days=$(( $timer / 60 / 60 / 24 ))
	local hours=$(( $timer / 60 / 60 % 24 ))
	local minutes=$(( $timer / 60 % 60 ))
	local seconds=$(( $timer % 60 ))

	(( $days > 0 )) && output="${days}d "
	(( $hours > 0 )) && output="${output}${hours}h "
	(( $minutes > 0 )) && output="${output}${minutes}m "

	output="${output}${seconds}s"

	printf " ${exec_time_prefix}${exec_time_color} ${output}"
}

# Show exit status of previous command
exit_code_section() {
	local exit_status

	if [[ "$RETVAL" -eq 0 ]]; then
		exit_status="${exit_ok_color}"
	else
		exit_status="${exit_bad_color}"
	fi

	echo -e "${exit_status}${exit_symbol} "
}

######################
### POINT OF ENTRY ###
######################

# Compose prompt
prompt() {
	RETVAL=$?
	printf "${bold}$(user_section)$(dir_section)$(git_section)$(exec_time_section)${newline}$(exit_code_section)${reset}"
}

# Stop timer for execution duration calculation
PROMPT_COMMAND=timer_stop

# Set PS1
export PS1="\$(prompt)"
